# Generated by Django 5.1.1 on 2024-12-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='prof_pic'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
