# Generated by Django 5.1.1 on 2024-12-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='program',
            field=models.CharField(default='Unrecorded', max_length=100, null=True),
        ),
    ]
