# Generated by Django 5.1.1 on 2024-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=16)),
                ('seating_capacity', models.IntegerField(max_length=10)),
                ('hasAirConditioner', models.BooleanField()),
                ('hasInternet', models.BooleanField()),
                ('hasTelevision', models.BooleanField()),
            ],
        ),
    ]
