# Generated by Django 5.1.1 on 2024-10-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaces',
            name='seating_capacity',
            field=models.IntegerField(),
        ),
    ]
