# Generated by Django 5.1.1 on 2024-10-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_alter_spaces_seating_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=16)),
                ('seating_capacity', models.IntegerField()),
                ('hasAirConditioner', models.BooleanField()),
                ('hasInternet', models.BooleanField()),
                ('hasTelevision', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Spaces',
        ),
    ]
