# Generated by Django 5.1.1 on 2024-10-02 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_alter_space_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='picture',
        ),
        migrations.AddField(
            model_name='space',
            name='image_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='space',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
