# Generated by Django 5.1.1 on 2024-10-02 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_space_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='hasAirConditioner',
            new_name='has_air_conditioner',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='hasInternet',
            new_name='has_internet',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='hasTelevision',
            new_name='has_television',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='image_url',
            new_name='main_image_url',
        ),
        migrations.AddField(
            model_name='space',
            name='fifth_image_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='fourth_image_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='second_image_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='sixth_image_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='third_image_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
