# Generated by Django 5.1.1 on 2024-10-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_rename_item_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='category',
        ),
        migrations.RemoveField(
            model_name='space',
            name='type',
        ),
        migrations.AddField(
            model_name='space',
            name='category',
            field=models.ManyToManyField(related_name='spaces', to='space.category'),
        ),
        migrations.AddField(
            model_name='space',
            name='type',
            field=models.ManyToManyField(related_name='spaces', to='space.type'),
        ),
    ]
