# Generated by Django 5.1.1 on 2024-10-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_remove_space_category_remove_space_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
