# Generated by Django 5.1.1 on 2024-10-14 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_space_is_booked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='space',
            name='category',
            field=models.ManyToManyField(related_name='space', to='space.category'),
        ),
        migrations.AlterField(
            model_name='space',
            name='fifth_image',
            field=models.ImageField(blank=True, null=True, upload_to='space_images'),
        ),
        migrations.AlterField(
            model_name='space',
            name='fourth_image',
            field=models.ImageField(blank=True, null=True, upload_to='space_images'),
        ),
        migrations.AlterField(
            model_name='space',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='space_images'),
        ),
        migrations.AlterField(
            model_name='space',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='space_images'),
        ),
        migrations.AlterField(
            model_name='space',
            name='sixth_image',
            field=models.ImageField(blank=True, null=True, upload_to='space_images'),
        ),
        migrations.AlterField(
            model_name='space',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='space_images'),
        ),
        migrations.AlterField(
            model_name='space',
            name='type',
            field=models.ManyToManyField(related_name='space', to='space.type'),
        ),
    ]
