# Generated by Django 5.1.1 on 2024-10-14 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_alter_space_booked_by_alter_space_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='book_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='space',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='space',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
