# Generated by Django 5.1.1 on 2024-12-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='is_read',
        ),
        migrations.AddField(
            model_name='conversation',
            name='receiver_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sender_read',
            field=models.BooleanField(default=True),
        ),
    ]
