# Generated by Django 5.1.1 on 2024-12-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_alter_conversation_receiver_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='receiver_read',
            new_name='is_read',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='sender_read',
        ),
    ]
