# Generated by Django 5.1.1 on 2024-10-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='first_name',
            field=models.CharField(default='Unkown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='last_name',
            field=models.CharField(default='Unkown', max_length=50),
            preserve_default=False,
        ),
    ]
