# Generated by Django 5.1.1 on 2024-10-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Spaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('schedule', models.CharField(max_length=100)),
            ],
        ),
    ]
