# Generated by Django 5.1.1 on 2024-10-14 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_admin_spaces'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_Spaces',
        ),
        migrations.AddField(
            model_name='space',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
